spring:
  application:
    name: catalog
  datasource:
    url: jdbc:postgresql://localhost:5433/clubs
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 4
server:
  port: 9091
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 20
      min-spare: 5
